// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function ApplyDiff(arg1:string,arg2:string):Promise<void>;

export function ApplyMultiDiff(arg1:string,arg2:Array<string>):Promise<void>;

export function ArchiveBackupFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BackupOrDiff(arg1:string,arg2:string):Promise<void>;

export function CopyBackupFile(arg1:string,arg2:string):Promise<void>;

export function CreateDiff(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDiffList(arg1:string,arg2:string):Promise<Array<main.DiffFileInfo>>;

export function GetFileSize(arg1:string):Promise<number>;

export function GetI18N():Promise<Record<string, string>>;

export function GetLanguageText(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectAnyFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SelectBackupFolder():Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;
