// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveBackupFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CopyBackupFile(arg1:string,arg2:string):Promise<void>;

export function GetI18N():Promise<Record<string, string>>;

export function GetLanguage():Promise<string>;

export function GetLanguageText(arg1:string):Promise<string>;

export function SelectBackupFolder():Promise<string>;

export function SelectWorkFile():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;
