// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDiff(arg1, arg2) {
  return window['go']['main']['App']['ApplyDiff'](arg1, arg2);
}

export function ApplyMultiDiff(arg1, arg2) {
  return window['go']['main']['App']['ApplyMultiDiff'](arg1, arg2);
}

export function ArchiveBackupFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ArchiveBackupFile'](arg1, arg2, arg3);
}

export function BackupOrDiff(arg1, arg2) {
  return window['go']['main']['App']['BackupOrDiff'](arg1, arg2);
}

export function CopyBackupFile(arg1, arg2) {
  return window['go']['main']['App']['CopyBackupFile'](arg1, arg2);
}

export function CreateDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDiff'](arg1, arg2, arg3);
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiffList(arg1, arg2) {
  return window['go']['main']['App']['GetDiffList'](arg1, arg2);
}

export function GetI18N() {
  return window['go']['main']['App']['GetI18N']();
}

export function GetLanguageText(arg1) {
  return window['go']['main']['App']['GetLanguageText'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectAnyFile(arg1, arg2) {
  return window['go']['main']['App']['SelectAnyFile'](arg1, arg2);
}

export function SelectBackupFolder() {
  return window['go']['main']['App']['SelectBackupFolder']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}
