// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveBackupFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ArchiveBackupFile'](arg1, arg2, arg3);
}

export function CopyBackupFile(arg1, arg2) {
  return window['go']['main']['App']['CopyBackupFile'](arg1, arg2);
}

export function GetI18N() {
  return window['go']['main']['App']['GetI18N']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLanguageText(arg1) {
  return window['go']['main']['App']['GetLanguageText'](arg1);
}

export function SelectBackupFolder() {
  return window['go']['main']['App']['SelectBackupFolder']();
}

export function SelectWorkFile() {
  return window['go']['main']['App']['SelectWorkFile']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}
