// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyBsdiff(arg1, arg2) {
  return window['go']['main']['App']['ApplyBsdiff'](arg1, arg2);
}

export function ApplyHdiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyHdiff'](arg1, arg2, arg3);
}

export function ApplyHdiffWrapper(arg1, arg2) {
  return window['go']['main']['App']['ApplyHdiffWrapper'](arg1, arg2);
}

export function ApplyMultiBsdiff(arg1, arg2) {
  return window['go']['main']['App']['ApplyMultiBsdiff'](arg1, arg2);
}

export function ApplyMultiDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyMultiDiff'](arg1, arg2, arg3);
}

export function ArchiveBackupFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ArchiveBackupFile'](arg1, arg2, arg3, arg4);
}

export function BackupOrBsdiff(arg1, arg2) {
  return window['go']['main']['App']['BackupOrBsdiff'](arg1, arg2);
}

export function BackupOrDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['BackupOrDiff'](arg1, arg2, arg3);
}

export function BackupOrHdiff(arg1, arg2) {
  return window['go']['main']['App']['BackupOrHdiff'](arg1, arg2);
}

export function CopyBackupFile(arg1, arg2) {
  return window['go']['main']['App']['CopyBackupFile'](arg1, arg2);
}

export function CreateBsdiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBsdiff'](arg1, arg2, arg3);
}

export function CreateHdiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateHdiff'](arg1, arg2, arg3);
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function GetBackupList(arg1, arg2) {
  return window['go']['main']['App']['GetBackupList'](arg1, arg2);
}

export function GetBsdiffMaxFileSize() {
  return window['go']['main']['App']['GetBsdiffMaxFileSize']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function GetHdiffList(arg1, arg2) {
  return window['go']['main']['App']['GetHdiffList'](arg1, arg2);
}

export function GetI18N() {
  return window['go']['main']['App']['GetI18N']();
}

export function GetLanguageText(arg1) {
  return window['go']['main']['App']['GetLanguageText'](arg1);
}

export function GetRestorePreviousState() {
  return window['go']['main']['App']['GetRestorePreviousState']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RestoreArchive(arg1, arg2) {
  return window['go']['main']['App']['RestoreArchive'](arg1, arg2);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectAnyFile(arg1, arg2) {
  return window['go']['main']['App']['SelectAnyFile'](arg1, arg2);
}

export function SelectBackupFolder() {
  return window['go']['main']['App']['SelectBackupFolder']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetRestorePreviousState(arg1) {
  return window['go']['main']['App']['SetRestorePreviousState'](arg1);
}

export function ToggleCompactMode(arg1) {
  return window['go']['main']['App']['ToggleCompactMode'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
