// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function ApplyBsdiff(arg1:string,arg2:string):Promise<void>;

export function ApplyHdiff(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ApplyHdiffWrapper(arg1:string,arg2:string):Promise<void>;

export function ApplyMultiBsdiff(arg1:string,arg2:Array<string>):Promise<void>;

export function ApplyMultiDiff(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function ArchiveBackupFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function BackupOrBsdiff(arg1:string,arg2:string):Promise<void>;

export function BackupOrDiff(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BackupOrHdiff(arg1:string,arg2:string):Promise<void>;

export function CopyBackupFile(arg1:string,arg2:string):Promise<void>;

export function CreateBsdiff(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateHdiff(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateNewGeneration(arg1:string,arg2:number,arg3:string):Promise<string>;

export function DirExists(arg1:string):Promise<boolean>;

export function FindLatestBaseDir(arg1:string):Promise<string|number>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetAutoBaseGenerationThreshold():Promise<number>;

export function GetBackupList(arg1:string,arg2:string):Promise<Array<main.BackupItem>>;

export function GetBsdiffMaxFileSize():Promise<number>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConfigDir():Promise<string>;

export function GetFileSize(arg1:string):Promise<number>;

export function GetHdiffList(arg1:string,arg2:string):Promise<Array<main.DiffFileInfo>>;

export function GetI18N():Promise<Record<string, string>>;

export function GetLanguageText(arg1:string):Promise<string>;

export function GetRestorePreviousState():Promise<boolean>;

export function IsBaseAvailable(arg1:string,arg2:string):Promise<boolean>;

export function OpenDirectory(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ResolveGenerationDir(arg1:string,arg2:string):Promise<string>;

export function RestoreArchive(arg1:string,arg2:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectAnyFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SelectBackupFolder():Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetRestorePreviousState(arg1:boolean):Promise<void>;

export function ToggleCompactMode(arg1:boolean):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
